import fs from 'node:fs/promises'
const raw=JSON.parse((await fs.readFile('scripts/batch-ocr.local.json','utf8')).replace(/^\uFEFF/,''))
// Human-reviewed scene grouping. Numbers refer to the stable sorted inventory.
const groups=[
 [[1],'d','CM Block, Salt Lake Sector V, Bidhannagar','Litter and stacked paving pieces reduce the clear space beside the wall and pillar. Please clear loose waste and inspect the walking surface.'],
 [[2,3,7],'p,w','CM Block, Salt Lake Sector V, Bidhannagar','Multiple water-filled potholes and broken asphalt are visible on this road section. Please inspect and repair the surface and drainage.'],
 [[6],'d','CI-63, Chavlpatty Road, Sector 2, Bidhannagar','Litter and leaf debris have accumulated along the road edge beside the raised pavement.'],
 [[8],'p,b','Beside Rashmela Ground, Cooch Behar','The lane has multiple worn and broken patches, loose aggregate and shallow depressions. Surface repairs are requested.'],
 [[9,11],'p,w','Burirpat, Khagrabari, Cooch Behar','Potholes and broken road patches contain standing water along the residential lane.'],
 [[10,12],'r,d','Burirpat, Khagrabari, Cooch Behar','An open roadside drainage channel contains dark standing water, with litter accumulating along its edge. Please clean and inspect drainage.'],
 [[13,63,65],'b','4A, Nayapatti Main Road, AN Block, Sector V, Bidhannagar','The market-side road surface is badly worn, with loose stone and uneven patches beside the pedestrian route.'],
 [[15],'b,w','NP 16, AN Block, Sector V, Bidhannagar','The photographed ground beside the road is deeply rutted and holds muddy water. Please inspect this access area; its maintenance boundary is not verified.'],
 [[16,33,76],'d','AN Block Road, Sector V, Bidhannagar','Loose construction fragments, discarded boards and timber are piled beside the road. Please remove waste and restore a clear walking edge.'],
 [[17,78],'d','21/1, AN Block, Sector V, Bidhannagar','Mixed litter and discarded materials have accumulated along the roadside beside vegetation.'],
 [[18,154],'d','A-I-276, AI Block, Sector 2, Bidhannagar','A substantial accumulation of plastic litter, leaves and other waste is visible beside the boundary fence.'],
 [[19],'b,d','BI150, BI Block, Sector 2, Bidhannagar','The paved footway has displaced or missing blocks and scattered litter at the curb. Please inspect and repair the walking surface.'],
 [[20,32,87],'b,p','AI216 / NP 16, Chavlpatty Road, Bidhannagar','The road surface has extensive rough patches, exposed aggregate and uneven depressions along this short section.'],
 [[21,84,92],'d','BI62, Chavlpatty Road, BI Block, Sector 2, Bidhannagar','Sacks and mixed waste cover part of the paved roadside space beside the fence. Repeat views show the same affected area.'],
 [[24],'d','B-I-71, BI Block, Sector 2, Bidhannagar','Discarded packaging, branches and other waste are piled on the paved walking edge beside the fence.'],
 [[25],'d','BI-73, Chavlpatty Road, BI Block, Sector 2, Bidhannagar','Mixed litter and broken material cover the roadside strip beside the curb.'],
 [[27],'b','AI216, Chavlpatty Road, AI Block, Sector 2, Bidhannagar','The lane surface is uneven and worn, with shallow broken patches in the walking and vehicle route.'],
 [[29,80],'d','BI77, Chavlpatty Road, BI Block, Sector 2, Bidhannagar','Mixed discarded material and rubble have accumulated beside the fence and paved roadside edge.'],
 [[30],'d','AI216, Chavlpatty Road, AI Block, Sector 2, Bidhannagar','Bagged and loose rubbish occupy the roadside margin beside shops. Please clear the accumulated waste.'],
 [[31],'b,d','NP 16, AN Block, Sector V, Bidhannagar','The road edge beside the wall is rough and eroded, with scattered litter.'],
 [[34,38,85],'d','AN Block Road, Sector V, Bidhannagar','Broken tiles and masonry fragments are spread over the open roadside area beside the wall.'],
 [[36,37],'d','AN Block Road, Sector V, Bidhannagar','Rubble and discarded material surround a concrete slab and tree beside the road. Please clear the debris and inspect the slab area.'],
 [[39,77],'r,d','AI216, Chavlpatty Road, AI Block, Sector 2, Bidhannagar','An uncovered channel containing utility pipes is beside the walkway, with litter accumulated around its edge. Please inspect safe covering and clean the channel.'],
 [[40,74],'d','AN Block, Sector V, Bidhannagar','Broken masonry and other waste have accumulated beside a narrow paved path and vegetation.'],
 [[41],'b,d','NP 16, AN Block, Sector V, Bidhannagar','Paving blocks are missing or displaced below a roadside utility cabinet, leaving a gap and loose rubble. Please inspect the pavement; the photograph does not establish an electrical fault.'],
 [[42,67,69],'r,d','Kar Appartment, 04, Tarulia 1st Lane, Kestopur','The narrow drainage and walking edge beside the boundary wall is exposed and littered, with damaged or missing surface pieces.'],
 [[43],'d','4A, Nayapatti Main Road, AN Block, Sector V, Bidhannagar','Sacks, branches and broken material are piled along the roadside vegetation.'],
 [[44,73],'b','Chavlpatty Road / Nayapatti Main Road, Bidhannagar','A rough and uneven market road surface with exposed aggregate is visible in the pedestrian and vehicle route.'],
 [[45],'b,d','102, Mission Bazar, Krishnapur, Kestopur','Paving around a roadside tree guard is uneven and surrounded by litter. Please clear the waste and repair the walking edge.'],
 [[47,171],'b','Nayapatti Main Road, AN Block, Sector V, Bidhannagar','The busy market road has a long deteriorated edge with loose stones and an uneven walking surface.'],
 [[46,68],'r,d','Kar Appartment, 04, Tarulia 1st Lane, Kestopur','Litter is caught on and around the mesh-covered channel. Please remove the waste and inspect the drainage opening and cover.'],
 [[48,49,72],'r,d','Canal 2nd Lane, Mission Bazar, Krishnapur, Kestopur','Broken slabs, rubble and litter surround the roadside drain near a handpump. Open gaps interrupt the walking surface.'],
 [[50],'d','Kar Appartment, 04, Tarulia 1st Lane, Kestopur','A bag of plant cuttings and loose vegetation debris are beside the handpump and walking edge. Please clear accumulated waste.'],
 [[52,70],'b','Mission Bazar, Krishnapur, Kestopur','Interlocking paving has sunk or broken across the market passage, leaving an uneven strip in the route used by pedestrians and vehicles.'],
 [[53],'r,d','Canal 2nd Lane, Mission Bazar, Krishnapur, Kestopur','An open drainage edge beside the building contains litter and loose debris. Please clean and inspect the channel and pedestrian crossing.'],
 [[54],'d','Mission Bazar, Krishnapur, Kestopur','Mixed rubbish is accumulated beside the wall at the market edge.'],
 [[55,89],'r,b','Mission Bazar, Krishnapur, Kestopur','Broken and displaced slabs leave an exposed drainage gap directly beside shop access. Please inspect and restore a continuous walking surface.'],
 [[56],'b','238, Nayapatti, Krishnapur, Bidhannagar','The market passage has rough broken patches and loose material near the roadside.'],
 [[57,58,60],'d','Mission Bazar, Krishnapur, Kestopur','Mixed litter, discarded panels and other material cover the strip beside the wall and bridge approach.'],
 [[62],'d','AN Block, Sector V, Bidhannagar','Litter is visible along the dark bank-side area. Please inspect and clear waste; the photograph does not establish the waterbody condition.'],
 [[64,86,88],'b,d','Nayapatti Main Road, AN Block, Sector V, Bidhannagar','The market-side road margin has extensive loose rubble and a broken, uneven surface that reduces usable walking space.'],
 [[71],'r','Krishnapur, Kestopur','A narrow open drainage channel with dark water runs beside the walking surface and shopfront. Please inspect safe covering and drainage.'],
 [[79,83],'p,b','BI77, Chavlpatty Road, BI Block, Sector 2, Bidhannagar','The road has worn patches and a pronounced uneven seam or depression across the photographed section.'],
 [[82],'o','BI-78, Chavlpatty Road, BI Block, Sector 2, Bidhannagar','Several roadside bollards are broken or leaning across the road surface. Please secure the area and repair the damaged bollards.'],
 [[90],'d','AN Block, Sector V, Bidhannagar','Discarded boards, packaging and other waste have accumulated beside the corrugated boundary at the road edge.'],
 [[91],'d','Canal 2nd Lane, Mission Bazar, Krishnapur, Kestopur','Open crates containing rubbish and loose litter are surrounded by rubble beside the roadside. Please clear the accumulation.'],
 [[93],'d','18, Nayapatti Main Road, AN Block, Sector V, Bidhannagar','Discarded cups and other mixed waste are piled at the roadside beneath a sign.'],
 [[94],'d','AI216, Chavlpatty Road, AI Block, Sector 2, Bidhannagar','Plastic litter and other rubbish are scattered over the roadside ground beside vegetation.'],
 [[95],'r','Canal 2nd Lane, Mission Bazar, Krishnapur, Kestopur','An open roadside drain is crossed by an improvised narrow slab or plank. Please inspect the crossing and provide safe drainage covering.'],
 [[96],'d','A-I-216, AI Block, Sector 2, Bidhannagar','Loose broken bricks and other rubble form a pile at the road edge.'],
 [[97,167],'d,b','263, Canal Side Road, AI Block, Sector 2, Kolkata','Branches, a cut log, discarded material and litter obstruct the paved roadside strip. The walking surface is also broken and uneven.'],
 [[99,157],'b,r','126, Nayapatti Main Road, AN Block, Sector V, Bidhannagar','The shop-side walking edge has broken slabs, loose bricks and uncovered gaps. Please inspect and repair the surface and drainage covering.'],
 [[100],'b,d','92, Nayapatti Main Road, AN Block, Sector V, Bidhannagar','The pavement edge around the pole is broken and covered with loose rubble and litter.'],
 [[101,109],'d','Tarulia, West Bengal','A large accumulation of mixed rubbish is spread across the open roadside area. Please arrange removal and inspect the site.'],
 [[102],'r,b','102, Mission Bazar, Krishnapur, Kestopur','A broken or displaced cover leaves an open gap beside the building access ramp. Please inspect and repair the drainage and walking edge.'],
 [[103],'w,b','Mission Bazar, Krishnapur, Kestopur','Water is pooled along the broken market-side walking edge beside displayed goods. Please inspect the surface and drainage.'],
 [[104,105,108],'d','Tarulia 2nd Lane, Krishnapur, Kestopur','Mixed litter is scattered along the vegetated roadside strip and around a utility pole.'],
 [[106],'p,b','Krishnapur Main Road, Tarulia, Kestopur','An elongated broken patch and pothole interrupt the narrow lane surface.'],
 [[107],'d','Tarulia 2nd Lane, Krishnapur, Kestopur','A large pile of mixed rubbish has accumulated beside vegetation near the road.'],
 [[110],'d','Tarulia, Krishnapur, Kestopur','Branches and scattered litter have accumulated along the vegetated road edge.'],
 [[112],'b','Tarulia, Krishnapur, Kestopur','A rough broken band of asphalt and loose aggregate crosses part of the road.'],
 [[113,183],'d','Chandiberia Main Road, Tarulia, Krishnapur, Kestopur','Sacks, discarded furniture or panels and loose rubbish occupy the roadside space beside the boundary.'],
 [[114,117],'r,d','1, Tarulia Road, Krishnapur, Kestopur','An exposed drainage edge beside the wall contains litter, vegetation and discarded material. Please clear and inspect the channel.'],
 [[115],'b','Tarulia, Krishnapur, Newtown','The residential road surface is extensively worn and rough with exposed aggregate.'],
 [[116],'d','Ka-147, Chandiberia Main Road, Tarulia','Mixed litter and broken material have accumulated beside vegetation at the roadside.'],
 [[118,121],'r,d','RGM 41/1, Tarulia, Krishnapur, Kestopur','The roadside drain is mostly uncovered, with only a small slab crossing. Litter and stored poles lie along the edge. Please inspect safe covering and clear waste.'],
 [[119,179],'p,b','Tarulia, West Bengal','An elongated pothole or failed repair patch leaves an uneven surface in the lane near drainage grates.'],
 [[120],'p','Chandiberia Main Road, Tarulia, Krishnapur, Kestopur','A clearly visible pothole lies near a circular road cover. Please repair the depression without obstructing drainage access.'],
 [[122,123],'b','2, Thakdari Road, Tarulia, Krishnapur, Newtown','Broken and worn paving creates an uneven patch at the market road junction.'],
 [[124],'r,b','Tarulia, West Bengal','A damaged or displaced slab leaves an open gap beside utility poles at the road edge. Please inspect the drainage cover and walking surface.'],
 [[125,127],'b','1st, Thakdari Road, Tarulia, Krishnapur','The narrow lane has worn, uneven surface patches near raised building entrances.'],
 [[128,130],'b','AA-11, Tarulia, Krishnapur, Kestopur','The lane surface is uneven and deteriorated, with rough patches and shallow depressions.'],
 [[129],'d','Tarulia, Krishnapur, Newtown','Loose litter is scattered beside the raised roadside edge and utility pole.'],
 [[131],'r,d','BB-18, Tarulia, Krishnapur, Kestopur','An open water-filled channel beside the road is bordered by vegetation, litter and loose poles. Please inspect and clear drainage.'],
 [[132],'d','Krishnapur Main Road, Tarulia, Kestopur','Discarded packaging and cups are accumulated along the paved edge beside a food stall.'],
 [[134],'r,b','2, Thakdari Road, Tarulia, Krishnapur, Newtown','An uncovered hole and broken paving are visible beside a utility pole and shop entrance. Please secure the opening and inspect the drainage cover.'],
 [[135],'b,d','5, Tarulia, Krishnapur, Kestopur','The narrow lane has a heavily broken surface covered with loose bricks, tile fragments and litter.'],
 [[136],'b,w','BB-18, Tarulia, Krishnapur, Kestopur','Deep tyre ruts and muddy standing water are visible on the roadside ground beside a parked vehicle. Please inspect this access surface.'],
 [[139,176],'d','Tarulia, Krishnapur, Kestopur','Mixed litter and broken material have accumulated around roadside poles and along the walking edge.'],
 [[142],'r,d','102, Mission Bazar, Krishnapur, Kestopur','Loose waste and rubble surround an exposed gap beside a pole and narrow crossing. Please clear waste and inspect drainage covering.'],
 [[143,149],'d,b','102, Mission Bazar, Krishnapur, Kestopur','Litter and loose debris are visible along a damaged paved edge beside the shopfront and pole.'],
 [[144,177],'b,d','AA-11, Tarulia, Krishnapur, Kestopur','The roadside surface below utility boxes is broken and littered, with cables hanging close to the edge. Please inspect safe access; the photographs do not establish whether any cable is live.'],
 [[145,168],'d','86, Krishnapur, Kestopur','Discarded packaging and other rubbish have accumulated beside and beneath the market stall frontage.'],
 [[146],'r,w','Krishnapur, Kestopur','Standing dirty-looking water surrounds a drainage grate beside the shopfront. Please inspect drainage and remove accumulated waste.'],
 [[147,156],'p,b','Kestopur Jora Bridge, Mission Bazar, Krishnapur','Broken and sunken road and paving patches interrupt the busy market junction.'],
 [[148],'p,w','Rajbanshi Para, Krishnapur, Kestopur','A broad pothole in the residential lane contains standing water.'],
 [[150,165,166],'w,r,d','86, Krishnapur, Kestopur','Standing water, litter and broken or incomplete drainage covering are visible beside the food-stall frontage. Please clear waste and inspect the drain and walking surface. The source of the water is unverified.'],
 [[151],'b','Thakdari Road, Rajbanshi Para, Krishnapur, Kestopur','Broken paving and loose aggregate are visible at the road edge.'],
 [[152],'d','86, Krishnapur, Kestopur','Litter has accumulated in the vegetation along the raised roadside edge.'],
 [[153],'d','Krishnapur, Kestopur','Sacks and loose discarded material occupy the narrow roadside space beside the wall.'],
 [[158],'d,w','Mission Bazar, Krishnapur, Kestopur','Litter, rubble and a small pool of water are visible beside stored material at the market edge.'],
 [[159],'b,d','159, Nayapatti, AN Block, Sector V, Bidhannagar','The roadside walking edge has broken paving, loose bricks and litter beside the building entrance.'],
 [[160],'p,b','86, Krishnapur, Kestopur','A broad broken depression crosses part of the lane and leaves an uneven walking surface.'],
 [[161],'b,d','93, Nayapatti Main Road, AN Block, Sector V, Bidhannagar','The narrow road has worn and eroded edges with loose debris and litter beside building entrances.'],
 [[162,164],'d','Rajbanshi Para, Krishnapur, Kestopur','Sacks, cut leaves, rubble and scattered rubbish have accumulated along the lane beside walls and trees.'],
 [[163],'r,d','86, Krishnapur, Kestopur','An open drain directly beside the lane contains packaging and other waste. The adjacent slab edge is broken. Please clear and inspect safe covering.'],
 [[169],'b','Street Number 25, Mission Bazar, Krishnapur, Kestopur','The lane has heavily damaged paving with loose and exposed bricks and an uneven surface.'],
 [[170,75],'w,b','Mission Bazar, Krishnapur, Kestopur','Water covers substantial broken patches of the market passage beside vegetable stalls. Please inspect drainage and repair the surface; the water source is not established.'],
 [[172],'d','BB-8, Kestopur Canal Side Road, Tarulia','A large accumulation of mixed waste covers the open area beside vegetation and buildings.'],
 [[173],'d','102, Mission Bazar, Krishnapur, Kestopur','Mixed rubbish and broken material are piled beside a wall and temporary boundary.'],
 [[174,141],'d','Mission Bazar, Krishnapur, Kestopur','Loose construction fragments, sacks and litter are piled at the road edge beside a wall and poles. Please inspect and clear the loose waste.'],
 [[175],'d','BB-16, Tarulia, Krishnapur, Kestopur','Discarded cardboard packaging and other litter are visible in roadside vegetation.'],
 [[178],'m,r,d','1, Tarulia Road, Krishnapur, Kestopur','A circular manhole is completely uncovered beside the walking surface, with an exposed adjacent drain and scattered rubbish. Please urgently secure the opening and restore a suitable cover.'],
 [[181],'d','Tarulia 1st Lane, Krishnapur, Kestopur','A large pile of cut branches and scattered litter occupies the roadside space.'],
 [[182],'b,d','Tarulia, Krishnapur, Kestopur','The paved roadside strip has cracked or displaced slabs beside accumulated branches and a disused-looking cart. Please inspect the surface and clear loose debris.'],
 [[184],'r,d','Krishnapur Main Road, Tarulia, Kestopur','Broken drain covering leaves an exposed gap containing discarded cups and litter beside the walking surface.'],
 [[186],'r,d','Tarulia, Krishnapur, Kestopur','Displaced slabs and mixed rubbish surround an exposed roadside drainage gap. Please clean and restore safe covering.'],
 [[187],'r,d','Tarulia 2nd Lane, Krishnapur, Kestopur','An open drain with dark water runs beside the building and road. Litter and broken material line the edge, with a narrow plank crossing. Please inspect drainage and safe covering.'],
]
const overrides={
 3:[22.581628,88.42949,'20:36'],5:[22.581518,88.429372,'20:35'],12:[26.34201,89.450479,'13:46'],30:[22.584524,88.435222,'18:25'],39:[22.58466,88.435084,'18:24'],50:[22.586618,88.437596,'18:43'],53:[22.586162,88.437375,'18:42'],65:[22.584795,88.435976,'18:34'],69:[22.586856,88.437765,'18:44'],71:[22.585247,88.437268,'18:40'],96:[22.584614,88.434811,'20:06'],107:[22.585726,88.440436,'19:40'],108:[22.585968,88.439846,'19:38'],112:[22.588502,88.438672,'19:29'],113:[22.588307,88.438697,'19:31'],119:[22.586391,88.438933,'19:23'],121:[22.587403,88.438594,'19:26'],122:[22.585811,88.439115,'19:22'],124:[22.586368,88.439003,'19:23'],127:[22.586278,88.439089,'19:23'],131:[22.585459,88.439247,'19:21'],139:[22.585676,88.43805,'19:14'],142:[22.585722,88.437639,'18:59'],144:[22.585031,88.439281,'19:19'],152:[22.586519,88.436844,'18:49'],159:[22.583815,88.436778,'20:01'],173:[22.585757,88.4374,'18:58'],174:[22.585679,88.438347,'19:15'],177:[22.58503,88.439287,'19:19'],179:[22.586395,88.438908,'19:24'],187:[22.585711,88.440492,'19:40']
}
const exclusions={
 4:'Water beneath structure; unclear whether this is a flooded public route or an intended water channel.',
 5:'Additional view of potholes already represented by photos 2, 3 and 7; three-photo limit.',
 14:'Resting animals and bridge scene do not establish a reportable defect.',
 22:'Additional view of waste area represented by photos 21, 84 and 92; three-photo limit.',
 23:'Additional view of waste area represented by photos 21, 84 and 92; three-photo limit.',
 26:'Motion blur prevents reliable scene assessment.',
 28:'Additional view of waste area represented by photos 21, 84 and 92; three-photo limit.',
 35:'Stored cart and covered material; no distinct confirmed road defect.',
 51:'Blurred close-up without a clear reportable defect.',
 59:'Bridge overview does not establish a structural defect.',
 61:'General street overview without a distinct confirmed defect.',
 66:'Bridge overview does not establish a structural defect.',
 81:'Too dark to establish a distinct defect.',
 98:'Vendor scene without a distinct confirmed road defect.',
 111:'Blurred close-up without a clear reportable defect.',
 126:'Bins beside fence; no distinct waste overflow or road defect established.',
 133:'Heavy motion blur.',137:'People obscure the scene; clearer related view retained as photo 141.',
 138:'Heavy motion blur.',140:'Heavy motion blur.',
 155:'Food-stall interior; no distinct road issue confidently established.',
 180:'Headlight glare obscures the road surface.',185:'Motion blur; nearby waste is documented by clearer views.'
}
function metadata(n){
 const t=raw[n-1].text.replace(/\uFFFD/g,''),lat=t.match(/Lat\s+(\d+\.\d+)/i),lng=t.match(/Long\s+(\d+\.\d+)/i),tm=t.match(/(\d{2})[:.](\d{2})\s*([AP])M/i)
 let coords=overrides[n]
 if(!coords){if(!lat||!lng||!tm)throw Error(`Metadata needs review: ${n}`);coords=[+lat[1],+lng[1],`${String((+tm[1]%12)+(tm[3].toUpperCase()==='P'?12:0)).padStart(2,'0')}:${tm[2]}`]}
 if(coords[0]<22||coords[0]>27||coords[1]<88||coords[1]>90)throw Error(`Coordinates out of range: ${n}`)
 return {lat:coords[0],lng:coords[1],captured:`2026-09-${n<=7?'05':'06'}T${coords[2]}:00+05:30`}
}
const types={d:'debris_on_road',p:'pothole',w:'waterlogging',r:'broken_drainage',b:'bad_road_quality',m:'open_manhole',o:'other'}
const seen=new Set(),manifest=groups.map(([ids,t,address,description])=>{
 for(const n of ids){if(seen.has(n)||exclusions[n])throw Error(`Duplicate classification ${n}`);seen.add(n)}
 const stamps=ids.map(metadata)
 return {sourceIndices:ids,photos:ids.map(n=>raw[n-1].file),types:t.split(',').map(x=>types[x]),...stamps[0],captured:stamps.map(x=>x.captured),photoLocations:stamps.map(({lat,lng})=>({lat,lng})),city:ids[0]>=8&&ids[0]<=12?'Cooch Behar':'Kolkata',state:'West Bengal',address:address+', West Bengal, India (area from photo stamp; not independently verified)',description}
})
for(let n=1;n<=raw.length;n++)if(!seen.has(n)&&!exclusions[n])throw Error(`Unclassified photo ${n}`)
await fs.writeFile('scripts/photo-reports-west-bengal.local.json',JSON.stringify(manifest,null,2))
await fs.writeFile('scripts/photo-review-west-bengal.local.json',JSON.stringify({sourceCount:raw.length,reportCount:manifest.length,selectedPhotos:seen.size,excluded:Object.entries(exclusions).map(([n,reason])=>({index:+n,file:raw[n-1].file,reason})),groups:manifest.map((x,i)=>({reportId:`photo-import-20260906-${String(i+18).padStart(2,'0')}`,photos:x.sourceIndices,address:x.address}))},null,2))
console.log(`Reviewed ${raw.length}: ${manifest.length} reports; ${seen.size} selected photos; ${Object.keys(exclusions).length} excluded/redundant.`)
